import { z } from 'zod';

const PathsSchema = z.object({
  auth: z.object({
    signIn: z.string().min(1),
    signUp: z.string().min(1),
    verifyMfa: z.string().min(1),
    callback: z.string().min(1),
    passwordReset: z.string().min(1),
    passwordUpdate: z.string().min(1),
  }),
  app: z.object({
    home: z.string().min(1),
    personalAccountSettings: z.string().min(1),
    personalAccountAccessibility: z.string().min(1),
    personalAccountBilling: z.string().min(1),
    personalAccountBillingReturn: z.string().min(1),
    accountHome: z.string().min(1),
    accountSettings: z.string().min(1),
    accountBilling: z.string().min(1),
    accountMembers: z.string().min(1),
    accountClients: z.string().min(1),
    accountJobs: z.string().min(1),
    accountInvoices: z.string().min(1),
    accountInvoiceEdit: z.string().min(1),
    accountSchedule: z.string().min(1),
    accountJobDetail: z.string().min(1),
    accountJobEdit: z.string().min(1),
    accountBillingReturn: z.string().min(1),
    accountFamilyCalendar: z.string().min(1),
    accountShopping: z.string().min(1),
    accountMealPlan: z.string().min(1),
    accountCommunitySchedule: z.string().min(1),
    accountCommunityTasks: z.string().min(1),
    accountCommunityNotes: z.string().min(1),
    joinTeam: z.string().min(1),
    onboarding: z.string().min(1),
  }),
});

const pathsConfig = PathsSchema.parse({
  auth: {
    signIn: '/auth/sign-in',
    signUp: '/auth/sign-up',
    verifyMfa: '/auth/verify',
    callback: '/auth/callback',
    passwordReset: '/auth/password-reset',
    passwordUpdate: '/update-password',
  },
  app: {
    home: '/app',
    personalAccountSettings: '/app/settings',
    personalAccountAccessibility: '/app/accessibility',
    personalAccountBilling: '/app/billing',
    personalAccountBillingReturn: '/app/billing/return',
    accountHome: '/app/work/[account]',
    accountSettings: `/app/work/[account]/settings`,
    accountBilling: `/app/work/[account]/billing`,
    accountMembers: `/app/work/[account]/members`,
    accountClients: `/app/work/[account]/clients`,
    accountJobs: `/app/work/[account]/jobs`,
    accountInvoices: `/app/work/[account]/invoices`,
    accountInvoiceEdit: `/app/work/[account]/invoices/[id]/edit`,
    accountSchedule: `/app/work/[account]/schedule`,
    accountJobDetail: `/app/work/[account]/jobs/[id]`,
    accountJobEdit: `/app/work/[account]/jobs/[id]/edit`,
    accountBillingReturn: `/app/work/[account]/billing/return`,
    accountFamilyCalendar: `/app/work/[account]/calendar`,
    accountShopping: `/app/work/[account]/shopping`,
    accountMealPlan: `/app/work/[account]/meal-plan`,
    accountCommunitySchedule: `/app/work/[account]/community/schedule`,
    accountCommunityTasks: `/app/work/[account]/community/tasks`,
    accountCommunityNotes: `/app/work/[account]/community/notes`,
    joinTeam: '/join',
    onboarding: '/onboarding',
  },
} satisfies z.infer<typeof PathsSchema>);

export default pathsConfig;
