import { z } from 'zod';

const PathsSchema = z.object({
  auth: z.object({
    signIn: z.string().min(1),
    signUp: z.string().min(1),
    verifyMfa: z.string().min(1),
    callback: z.string().min(1),
    passwordReset: z.string().min(1),
    passwordUpdate: z.string().min(1),
  }),
  app: z.object({
    home: z.string().min(1),
    personalPlanner: z.string().min(1),
    personalAccountSettings: z.string().min(1),
    personalAccountAccessibility: z.string().min(1),
    personalAccountBilling: z.string().min(1),
    personalAccountBillingReturn: z.string().min(1),
    accountHome: z.string().min(1),
    accountSettings: z.string().min(1),
    accountBrandSettings: z.string().min(1),
    accountBilling: z.string().min(1),
    accountMembers: z.string().min(1),
    accountClients: z.string().min(1),
    accountJobs: z.string().min(1),
    accountInvoices: z.string().min(1),
    accountInvoiceEdit: z.string().min(1),
    accountSchedule: z.string().min(1),
    accountTasks: z.string().min(1),
    accountTasksExtract: z.string().min(1),
    accountPipeline: z.string().min(1),
    accountJobDetail: z.string().min(1),
    accountJobEdit: z.string().min(1),
    accountBillingReturn: z.string().min(1),
    accountFamilyCalendar: z.string().min(1),
    accountShopping: z.string().min(1),
    accountMealPlan: z.string().min(1),
    accountCommunitySchedule: z.string().min(1),
    accountCommunityMeetupDetail: z.string().min(1),
    accountCommunityTasks: z.string().min(1),
    accountCommunityNotes: z.string().min(1),
    accountNotes: z.string().min(1),
    accountNoteDetail: z.string().min(1),
    accountDocs: z.string().min(1),
    accountDocDetail: z.string().min(1),
    accountFinances: z.string().min(1),
    accountFeedflowReviews: z.string().min(1),
    accountFeedflowWidgets: z.string().min(1),
    accountFeedflowVideos: z.string().min(1),
    accountFeedflowSocialAccounts: z.string().min(1),
    accountRanklyDashboard: z.string().min(1),
    accountRanklyProjects: z.string().min(1),
    accountRanklyProjectDetail: z.string().min(1),
    accountRanklyAlerts: z.string().min(1),
    accountRanklyResearch: z.string().min(1),
    accountSignaturesDashboard: z.string().min(1),
    accountSignaturesStaff: z.string().min(1),
    accountSignaturesStaffDetail: z.string().min(1),
    accountSignaturesTemplates: z.string().min(1),
    accountSignaturesTemplateDetail: z.string().min(1),
    accountSignaturesSettings: z.string().min(1),
    accountProperties: z.string().min(1),
    accountPropertyDetail: z.string().min(1),
    joinTeam: z.string().min(1),
    onboarding: z.string().min(1),
    workspaceSetup: z.string().min(1),
  }),
});

const pathsConfig = PathsSchema.parse({
  auth: {
    signIn: '/auth/sign-in',
    signUp: '/auth/sign-up',
    verifyMfa: '/auth/verify',
    callback: '/auth/callback',
    passwordReset: '/auth/password-reset',
    passwordUpdate: '/update-password',
  },
  app: {
    home: '/app',
    personalPlanner: '/app/planner',
    personalAccountSettings: '/app/settings',
    personalAccountAccessibility: '/app/accessibility',
    personalAccountBilling: '/app/billing',
    personalAccountBillingReturn: '/app/billing/return',
    accountHome: '/app/work/[account]',
    accountSettings: `/app/work/[account]/settings`,
    accountBrandSettings: `/app/work/[account]/settings/brand`,
    accountBilling: `/app/work/[account]/billing`,
    accountMembers: `/app/work/[account]/members`,
    accountClients: `/app/work/[account]/clients`,
    accountJobs: `/app/work/[account]/jobs`,
    accountInvoices: `/app/work/[account]/invoices`,
    accountInvoiceEdit: `/app/work/[account]/invoices/[id]/edit`,
    accountSchedule: `/app/work/[account]/schedule`,
    accountTasks: `/app/work/[account]/tasks`,
    accountTasksExtract: `/app/work/[account]/tasks/extract`,
    accountPipeline: `/app/work/[account]/pipeline`,
    accountJobDetail: `/app/work/[account]/jobs/[id]`,
    accountJobEdit: `/app/work/[account]/jobs/[id]/edit`,
    accountBillingReturn: `/app/work/[account]/billing/return`,
    accountFamilyCalendar: `/app/work/[account]/calendar`,
    accountShopping: `/app/work/[account]/shopping`,
    accountMealPlan: `/app/work/[account]/meal-plan`,
    accountCommunitySchedule: `/app/work/[account]/community/schedule`,
    accountCommunityMeetupDetail: `/app/work/[account]/community/schedule/[eventId]`,
    accountCommunityTasks: `/app/work/[account]/community/tasks`,
    accountCommunityNotes: `/app/work/[account]/community/notes`,
    accountNotes: `/app/work/[account]/notes`,
    accountNoteDetail: `/app/work/[account]/notes/[noteId]`,
    accountDocs: `/app/work/[account]/docs`,
    accountDocDetail: `/app/work/[account]/docs/[docId]`,
    accountFinances: `/app/work/[account]/finances`,
    accountFeedflowReviews: `/app/work/[account]/reviews`,
    accountFeedflowWidgets: `/app/work/[account]/widgets`,
    accountFeedflowVideos: `/app/work/[account]/videos`,
    accountFeedflowSocialAccounts: `/app/work/[account]/social/accounts`,
    accountRanklyDashboard: `/app/work/[account]/rankly/dashboard`,
    accountRanklyProjects: `/app/work/[account]/rankly/projects`,
    accountRanklyProjectDetail: `/app/work/[account]/rankly/projects/[projectId]`,
    accountRanklyAlerts: `/app/work/[account]/rankly/alerts`,
    accountRanklyResearch: `/app/work/[account]/rankly/research`,
    accountSignaturesDashboard: `/app/work/[account]/signatures`,
    accountSignaturesStaff: `/app/work/[account]/signatures/staff`,
    accountSignaturesStaffDetail: `/app/work/[account]/signatures/staff/[staffId]`,
    accountSignaturesTemplates: `/app/work/[account]/signatures/templates`,
    accountSignaturesTemplateDetail: `/app/work/[account]/signatures/templates/[templateId]`,
    accountSignaturesSettings: `/app/work/[account]/signatures/settings`,
    accountProperties: `/app/work/[account]/properties`,
    accountPropertyDetail: `/app/work/[account]/properties/[id]`,
    joinTeam: '/join',
    onboarding: '/onboarding',
    workspaceSetup: '/setup',
  },
} satisfies z.infer<typeof PathsSchema>);

export default pathsConfig;
