import { emptyWebsiteStyleSystem } from '../planning-types';
import { findSectionLibraryEntry } from '../section-library';
import { styleTokensRootCss } from './tokens-css';
import type { WebsiteExportFile, WebsiteExportInput } from './types';
import { pageRoute, pascalCase } from './types';

/** Astro starter: pages, section components, content collections, tokens CSS. */
export function buildAstroPack(input: WebsiteExportInput): WebsiteExportFile[] {
  const style = input.style ?? emptyWebsiteStyleSystem();
  const { tokens } = style;
  const files: WebsiteExportFile[] = [];

  files.push({
    path: 'astro/README.md',
    language: 'markdown',
    content: `# ${input.websiteName} — Astro starter

Generated by Ozer Site Studio.

\`\`\`bash
npm create astro@latest ${input.websiteName.toLowerCase().replace(/[^a-z0-9]+/g, '-')} -- --template minimal
# then copy the src/ and public/ files from this pack into the project
\`\`\`

- Section components live in \`src/components/sections/\`.
- Page copy lives in content collections (\`src/content/pages/\`) so editors change Markdown, not components.
- Design tokens are CSS variables in \`src/styles/tokens.css\`.
- \`public/llms.txt\` and JSON-LD are included from the SEO artefacts in this pack.
`,
  });

  files.push({
    path: 'astro/src/styles/tokens.css',
    language: 'css',
    content: `${styleTokensRootCss(tokens)}
body {
  background: var(--sb-canvas);
  color: var(--sb-ink);
  font-family: var(--sb-font-body);
}

h1, h2, h3, h4 {
  font-family: var(--sb-font-display);
}
`,
  });

  files.push({
    path: 'astro/src/content/config.ts',
    language: 'typescript',
    content: `import { defineCollection, z } from 'astro:content';

const pages = defineCollection({
  type: 'data',
  schema: z.object({
    title: z.string(),
    seoTitle: z.string().optional(),
    metaDescription: z.string().optional(),
    sections: z.array(
      z.object({
        component: z.string(),
        heading: z.string().optional(),
        body: z.string().optional(),
        cta: z.string().optional(),
      }),
    ),
  }),
});

export const collections = { pages };
`,
  });

  // Unique section components across all wireframes.
  const componentKeys = new Set<string>();
  for (const page of input.wireframes) {
    for (const section of page.sections) {
      const entry = findSectionLibraryEntry(section.libraryKey);
      componentKeys.add(entry?.key ?? 'generic-section');
    }
  }
  if (componentKeys.size === 0) componentKeys.add('generic-section');

  for (const key of componentKeys) {
    const entry = findSectionLibraryEntry(key);
    const componentName = pascalCase(entry?.label ?? key);
    files.push({
      path: `astro/src/components/sections/${componentName}.astro`,
      language: 'astro',
      content: `---
// ${entry?.label ?? 'Section'} — ${entry?.hint ?? 'generic section'}
interface Props {
  heading?: string;
  body?: string;
  cta?: string;
}
const { heading, body, cta } = Astro.props;
---

<section class="section ${key}">
  <div class="container">
    {heading && <h2>{heading}</h2>}
    {body && <p>{body}</p>}
    {cta && <a class="button" href="#">{cta}</a>}
    <slot />
  </div>
</section>

<style>
  .section {
    padding-block: var(--sb-space-12);
  }
  .container {
    max-width: 72rem;
    margin-inline: auto;
    padding-inline: 1.5rem;
  }
  .button {
    display: inline-block;
    background: var(--sb-color-primary);
    color: var(--sb-color-primary-contrast);
    border-radius: var(--sb-button-radius);
    padding: 0.75rem 1.5rem;
  }
</style>
`,
    });
  }

  for (const page of input.sitemap) {
    const wireframe = input.wireframes.find((item) => item.pageId === page.id);
    const seo = input.seoPages[page.id];
    const route = pageRoute(page);
    const filePath =
      route === '/'
        ? 'astro/src/pages/index.astro'
        : `astro/src/pages${route}.astro`;

    const imports = new Set<string>();
    const sectionTags: string[] = [];

    for (const section of wireframe?.sections ?? []) {
      const entry = findSectionLibraryEntry(section.libraryKey);
      const componentName = pascalCase(entry?.label ?? 'Generic Section');
      imports.add(
        `import ${componentName} from '../components/sections/${componentName}.astro';`,
      );
      const outline = section.copyOutline
        ? section.copyOutline.split('\n')[0]?.slice(0, 120)
        : section.title;
      sectionTags.push(
        `  <${componentName} heading=${JSON.stringify(section.title)} body=${JSON.stringify(outline ?? '')} />`,
      );
    }

    files.push({
      path: filePath,
      language: 'astro',
      content: `---
${[...imports].join('\n')}
const title = ${JSON.stringify(seo?.title || page.title)};
const description = ${JSON.stringify(seo?.metaDescription ?? page.description ?? '')};
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>{title}</title>
    <meta name="description" content={description} />
  </head>
  <body>
${sectionTags.join('\n') || '  <!-- No wireframe sections yet -->'}
  </body>
</html>
`,
    });
  }

  return files;
}
