import { emptyWebsiteStyleSystem } from '../planning-types';
import { findSectionLibraryEntry } from '../section-library';
import type { WebsiteExportFile, WebsiteExportInput } from './types';
import { pageRoute, pascalCase } from './types';

/** Next.js (App Router) starter: pages, section components, typed content config. */
export function buildNextPack(input: WebsiteExportInput): WebsiteExportFile[] {
  const style = input.style ?? emptyWebsiteStyleSystem();
  const { tokens } = style;
  const files: WebsiteExportFile[] = [];
  const cmsNote = input.brief?.cmsNeeded
    ? '\n- Brief flags a CMS requirement: wire the content config to Payload or Sanity (stub in `content/README.md`).'
    : '';

  files.push({
    path: 'next/README.md',
    language: 'markdown',
    content: `# ${input.websiteName} — Next.js starter

Generated by Ozer Site Studio.

\`\`\`bash
npx create-next-app@latest --ts --app --tailwind
# then copy app/, components/ and content/ from this pack
\`\`\`

- Section components: \`components/sections/\`
- Page content is a typed config in \`content/pages.ts\` — no CMS required to launch.${cmsNote}
- Design tokens: CSS variables in \`app/tokens.css\`.
- Serve \`llms.txt\` from \`public/\` and paste JSON-LD blocks into page metadata.
`,
  });

  files.push({
    path: 'next/app/tokens.css',
    language: 'css',
    content: `:root {
  --canvas: ${tokens.canvas};
  --atmosphere: ${tokens.atmosphere};
  --accent: ${tokens.accent};
  --contrast: ${tokens.contrast};
  --secondary: ${tokens.secondary};
  --radius: ${tokens.radius === 'sharp' ? '0px' : tokens.radius === 'round' ? '16px' : '8px'};
  --section-padding: ${tokens.spacingDensity === 'tight' ? '3rem' : tokens.spacingDensity === 'airy' ? '8rem' : '5rem'};
}
`,
  });

  // Typed content config from wireframes + SEO.
  const pagesConfig = input.sitemap.map((page) => {
    const wireframe = input.wireframes.find((item) => item.pageId === page.id);
    const seo = input.seoPages[page.id];
    return {
      route: pageRoute(page),
      title: page.title,
      seoTitle: seo?.title || page.title,
      metaDescription: seo?.metaDescription ?? '',
      sections: (wireframe?.sections ?? []).map((section) => {
        const entry = findSectionLibraryEntry(section.libraryKey);
        return {
          component: pascalCase(entry?.label ?? 'Generic Section'),
          heading: section.title,
          copyOutline: section.copyOutline ?? '',
        };
      }),
    };
  });

  files.push({
    path: 'next/content/pages.ts',
    language: 'typescript',
    content: `export type SectionContent = {
  component: string;
  heading: string;
  copyOutline: string;
};

export type PageContent = {
  route: string;
  title: string;
  seoTitle: string;
  metaDescription: string;
  sections: SectionContent[];
};

export const pages: PageContent[] = ${JSON.stringify(pagesConfig, null, 2)};
`,
  });

  // Unique section components.
  const componentNames = new Set<string>();
  for (const page of input.wireframes) {
    for (const section of page.sections) {
      const entry = findSectionLibraryEntry(section.libraryKey);
      componentNames.add(pascalCase(entry?.label ?? 'Generic Section'));
    }
  }
  if (componentNames.size === 0) componentNames.add('GenericSection');

  for (const name of componentNames) {
    files.push({
      path: `next/components/sections/${name}.tsx`,
      language: 'tsx',
      content: `export function ${name}({
  heading,
  body,
  cta,
}: {
  heading?: string;
  body?: string;
  cta?: string;
}) {
  return (
    <section className="[padding-block:var(--section-padding)]">
      <div className="mx-auto max-w-6xl px-6">
        {heading ? <h2 className="text-3xl font-semibold">{heading}</h2> : null}
        {body ? <p className="mt-4 max-w-2xl">{body}</p> : null}
        {cta ? (
          <a
            href="#"
            className="mt-6 inline-block rounded-[var(--radius)] bg-[var(--accent)] px-6 py-3 text-[var(--canvas)]"
          >
            {cta}
          </a>
        ) : null}
      </div>
    </section>
  );
}
`,
    });
  }

  // Page routes.
  for (const page of input.sitemap) {
    const wireframe = input.wireframes.find((item) => item.pageId === page.id);
    const seo = input.seoPages[page.id];
    const route = pageRoute(page);
    const filePath =
      route === '/' ? 'next/app/page.tsx' : `next/app${route}/page.tsx`;

    const imports = new Set<string>();
    const sectionTags: string[] = [];

    for (const section of wireframe?.sections ?? []) {
      const entry = findSectionLibraryEntry(section.libraryKey);
      const name = pascalCase(entry?.label ?? 'Generic Section');
      imports.add(
        `import { ${name} } from '${route === '/' ? '../components' : '../../components'}/sections/${name}';`,
      );
      const outline = section.copyOutline
        ? section.copyOutline.split('\n')[0]?.slice(0, 120)
        : '';
      sectionTags.push(
        `      <${name} heading=${JSON.stringify(section.title)} body=${JSON.stringify(outline ?? '')} />`,
      );
    }

    files.push({
      path: filePath,
      language: 'tsx',
      content: `${[...imports].join('\n')}

export const metadata = {
  title: ${JSON.stringify(seo?.title || page.title)},
  description: ${JSON.stringify(seo?.metaDescription ?? page.description ?? '')},
};

export default function Page() {
  return (
    <main>
${sectionTags.join('\n') || '      {/* No wireframe sections yet */}'}
    </main>
  );
}
`,
    });
  }

  return files;
}
