export {
  CONTRACT_SMART_FIELDS,
  DEFAULT_CONTRACT_EMAIL_BODY,
  DEFAULT_CONTRACT_EMAIL_SIGNATURE,
  DEFAULT_CONTRACT_EMAIL_SUBJECT,
  buildSmartFieldReplacements,
  formatContractDate,
  formatContractMoney,
  formatPaymentPlanText,
  hasSmartFieldTokens,
  listUnresolvedSmartFields,
  renderContractSmartFields,
  type SmartFieldContext,
  type SmartFieldDefinition,
} from '~/lib/contracts/smart-fields';
