/**
 * RICS Home Survey section catalogue (Level 2 + Level 3).
 * Keys stay stable for existing observations; ricsCode is the letter/element
 * used by templates, phrase banks, and GoReport imports.
 */
import type { BuildingSurveyTypeKey } from './survey-types';

export type SurveyLevel = 'l2' | 'l3';

export type BuildingSurveySection = {
  key: string;
  heading: string;
  group: string;
  letter: string;
  ricsCode: string;
  keywords: readonly string[];
  allowsRating: boolean;
  allowsPhotos: boolean;
  levels: readonly SurveyLevel[];
};

function section(partial: BuildingSurveySection): BuildingSurveySection {
  return partial;
}

export const BUILDING_SURVEY_SECTIONS: readonly BuildingSurveySection[] = [
  section({
    key: 'about_inspection',
    heading: 'About the inspection',
    group: 'A About the inspection',
    letter: 'A',
    ricsCode: 'A',
    keywords: ['inspection', 'survey date', 'weather', 'access', 'limitations'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'related_party',
    heading: 'Related party disclosure',
    group: 'A About the inspection',
    letter: 'A',
    ricsCode: 'A.related_party',
    keywords: ['related party', 'conflict of interest', 'disclosure'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'weather',
    heading: 'Weather',
    group: 'A About the inspection',
    letter: 'A',
    ricsCode: 'A.weather',
    keywords: ['weather', 'overcast', 'rainfall', 'dry'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'occupancy',
    heading: 'Status of the property',
    group: 'A About the inspection',
    letter: 'A',
    ricsCode: 'A.occupancy',
    keywords: ['occupied', 'unoccupied', 'vacant', 'furnished', 'vendor'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'overall_opinion',
    heading: 'Overall opinion',
    group: 'B Overall opinion',
    letter: 'B',
    ricsCode: 'B',
    keywords: ['overall', 'summary', 'opinion', 'condition rating'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'repairs_summary',
    heading: 'Summary of repairs',
    group: 'B Overall opinion',
    letter: 'B',
    ricsCode: 'B.repairs',
    keywords: ['repairs', 'cost guidance', 'allow £'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'further_investigations',
    heading: 'Further investigations',
    group: 'B Overall opinion',
    letter: 'B',
    ricsCode: 'B.further_investigations',
    keywords: ['further investigation', 'specialist', 'camera survey'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'documents_suggested',
    heading: 'Documents we may suggest',
    group: 'B Overall opinion',
    letter: 'B',
    ricsCode: 'B.documents',
    keywords: ['documents we may suggest', 'request before you sign'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'about_property',
    heading: 'About the property',
    group: 'C About the property',
    letter: 'C',
    ricsCode: 'C',
    keywords: [
      'property',
      'dwelling',
      'construction',
      'age',
      'tenure',
      'accommodation',
    ],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'property_type',
    heading: 'Type of property',
    group: 'C About the property',
    letter: 'C',
    ricsCode: 'C.type',
    keywords: [
      'detached',
      'semi-detached',
      'terrace',
      'bungalow',
      'flat',
      'maisonette',
      'apartment',
    ],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'year_built',
    heading: 'Approximate year the property was built',
    group: 'C About the property',
    letter: 'C',
    ricsCode: 'C.year_built',
    keywords: ['year the property was built', 'newly built', 'built in'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'year_extended',
    heading: 'Approximate year the property was extended',
    group: 'C About the property',
    letter: 'C',
    ricsCode: 'C.year_extended',
    keywords: ['extended', 'extension', 'conservatory added'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'year_converted',
    heading: 'Approximate year the property was converted',
    group: 'C About the property',
    letter: 'C',
    ricsCode: 'C.year_converted',
    keywords: ['converted', 'conversion'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'flats_info',
    heading: 'Information relevant to flats and maisonettes',
    group: 'C About the property',
    letter: 'C',
    ricsCode: 'C.flats',
    keywords: ['leasehold', 'service charge', 'managing agent', 'maisonette'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'construction',
    heading: 'Construction',
    group: 'C About the property',
    letter: 'C',
    ricsCode: 'C.construction',
    keywords: ['cavity', 'solid wall', 'foundations', 'pitched roof'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'means_of_escape',
    heading: 'Means of escape',
    group: 'C About the property',
    letter: 'C',
    ricsCode: 'C.means_of_escape',
    keywords: ['means of escape', 'fire escape', 'protected stair'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l3'],
  }),
  section({
    key: 'energy_efficiency_rating',
    heading: 'Energy efficiency rating',
    group: 'C About the property',
    letter: 'C',
    ricsCode: 'C.epc',
    keywords: ['epc', 'energy performance', 'energy efficiency rating'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'energy_efficiency_issues',
    heading: 'Issues relating to the energy efficiency rating',
    group: 'C About the property',
    letter: 'C',
    ricsCode: 'C.epc_issues',
    keywords: ['discrepancies to the assumptions in the epc'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'location',
    heading: 'Location',
    group: 'C Location and facilities',
    letter: 'C',
    ricsCode: 'C.location',
    keywords: ['location', 'neighbourhood', 'setting'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'location_grounds',
    heading: 'Grounds (location)',
    group: 'C Location and facilities',
    letter: 'C',
    ricsCode: 'C.grounds',
    keywords: ['plot', 'site', 'front garden', 'rear garden setting'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'facilities',
    heading: 'Facilities',
    group: 'C Location and facilities',
    letter: 'C',
    ricsCode: 'C.facilities',
    keywords: ['facilities', 'shops', 'transport', 'schools'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'local_environment',
    heading: 'Local environment',
    group: 'C Location and facilities',
    letter: 'C',
    ricsCode: 'C.local_environment',
    keywords: ['flood', 'radon', 'local environment', 'trees nearby'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'other_local_factors',
    heading: 'Other local factors',
    group: 'C Location and facilities',
    letter: 'C',
    ricsCode: 'C.other_local',
    keywords: ['other local factors'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l3'],
  }),
  section({
    key: 'other_energy_sources',
    heading: 'Other services or energy sources',
    group: 'C About the property',
    letter: 'C',
    ricsCode: 'C.other_energy_sources',
    keywords: [
      'photovoltaic',
      'solar water',
      'heat pump',
      'wind turbine',
      'feed-in',
    ],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'other_energy_matters',
    heading: 'Other energy matters',
    group: 'C About the property',
    letter: 'C',
    ricsCode: 'C.other_energy',
    keywords: ['renewable energy', 'co2', 'gas boilers 2035'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'outside_limitations',
    heading: 'Limitations to inspection (outside)',
    group: 'D Outside the property',
    letter: 'D',
    ricsCode: 'D.limitations',
    keywords: ['limitations to inspection', 'outside limitations'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'chimney_stacks',
    heading: 'Chimney stacks',
    group: 'D Outside the property',
    letter: 'D',
    ricsCode: 'D1',
    keywords: ['chimney', 'stack', 'flaunching', 'pot', 'flashing'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'roof_coverings',
    heading: 'Roof coverings',
    group: 'D Outside the property',
    letter: 'D',
    ricsCode: 'D2',
    keywords: ['roof', 'tile', 'slate', 'covering', 'ridge', 'valley'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'rainwater',
    heading: 'Rainwater pipes and gutters',
    group: 'D Outside the property',
    letter: 'D',
    ricsCode: 'D3',
    keywords: ['gutter', 'downpipe', 'rainwater', 'hopper'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'main_walls',
    heading: 'Main walls',
    group: 'D Outside the property',
    letter: 'D',
    ricsCode: 'D4',
    keywords: ['wall', 'brick', 'render', 'pointing', 'damp proof', 'cavity'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'windows',
    heading: 'Windows',
    group: 'D Outside the property',
    letter: 'D',
    ricsCode: 'D5',
    keywords: [
      'window',
      'windows',
      'glazing',
      'sash',
      'casement',
      'double glazed',
      'cill',
      'window cill',
    ],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'outside_doors',
    heading: 'Outside doors (including patio doors)',
    group: 'D Outside the property',
    letter: 'D',
    ricsCode: 'D6',
    keywords: ['door', 'patio', 'french door', 'threshold'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'conservatory_porches',
    heading: 'Conservatory and porches',
    group: 'D Outside the property',
    letter: 'D',
    ricsCode: 'D7',
    keywords: ['conservatory', 'porch', 'canopy'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'other_joinery',
    heading: 'Other joinery and finishes',
    group: 'D Outside the property',
    letter: 'D',
    ricsCode: 'D8',
    keywords: ['fascia', 'soffit', 'bargeboard', 'cladding', 'joinery'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'other_outside',
    heading: 'Other (outside)',
    group: 'D Outside the property',
    letter: 'D',
    ricsCode: 'D9',
    keywords: ['other outside', 'external other'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'inside_limitations',
    heading: 'Limitations to inspection (inside)',
    group: 'E Inside the property',
    letter: 'E',
    ricsCode: 'E.limitations',
    keywords: ['inside limitations', 'loft access not'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'roof_structure',
    heading: 'Roof structure',
    group: 'E Inside the property',
    letter: 'E',
    ricsCode: 'E1',
    keywords: ['roof structure', 'rafter', 'truss', 'loft', 'felt'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'ceilings',
    heading: 'Ceilings',
    group: 'E Inside the property',
    letter: 'E',
    ricsCode: 'E2',
    keywords: ['ceiling', 'plasterboard', 'lath and plaster'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'walls_partitions',
    heading: 'Walls and partitions',
    group: 'E Inside the property',
    letter: 'E',
    ricsCode: 'E3',
    keywords: ['partition', 'internal wall', 'plaster', 'lining'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'floors',
    heading: 'Floors',
    group: 'E Inside the property',
    letter: 'E',
    ricsCode: 'E4',
    keywords: ['floor', 'joist', 'screed', 'board', 'deflection'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'fireplaces',
    heading: 'Fireplaces, chimney breasts and flues',
    group: 'E Inside the property',
    letter: 'E',
    ricsCode: 'E5',
    keywords: ['fireplace', 'hearth', 'flue', 'chimney breast'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'built_in_fittings',
    heading: 'Built-in fittings',
    group: 'E Inside the property',
    letter: 'E',
    ricsCode: 'E6',
    keywords: [
      'fitted kitchen',
      'fitted',
      'cupboard',
      'wardrobe',
      'kitchen unit',
    ],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'woodwork',
    heading: 'Woodwork (for example, staircase joinery)',
    group: 'E Inside the property',
    letter: 'E',
    ricsCode: 'E7',
    keywords: ['staircase', 'banister', 'skirting', 'door lining', 'woodwork'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'bathroom_fittings',
    heading: 'Bathroom fittings',
    group: 'E Inside the property',
    letter: 'E',
    ricsCode: 'E8',
    keywords: ['bathroom', 'wc', 'basin', 'bath', 'shower', 'sanitary'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'other_inside',
    heading: 'Other (inside)',
    group: 'E Inside the property',
    letter: 'E',
    ricsCode: 'E9',
    keywords: ['other inside'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'services_limitations',
    heading: 'Limitations to inspection (services)',
    group: 'F Services',
    letter: 'F',
    ricsCode: 'F.limitations',
    keywords: ['services limitations'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'electricity',
    heading: 'Electricity',
    group: 'F Services',
    letter: 'F',
    ricsCode: 'F1',
    keywords: ['electric', 'consumer unit', 'fuse', 'socket', 'wiring', 'rcd'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'gas_oil',
    heading: 'Gas / oil',
    group: 'F Services',
    letter: 'F',
    ricsCode: 'F2',
    keywords: ['gas', 'oil', 'meter', 'boiler flue'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'water',
    heading: 'Water',
    group: 'F Services',
    letter: 'F',
    ricsCode: 'F3',
    keywords: ['water', 'stopcock', 'rising main', 'pipework'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'heating',
    heading: 'Heating',
    group: 'F Services',
    letter: 'F',
    ricsCode: 'F4',
    keywords: ['heating', 'boiler', 'radiator', 'thermostat', 'heat pump'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'water_heating',
    heading: 'Water heating',
    group: 'F Services',
    letter: 'F',
    ricsCode: 'F5',
    keywords: ['hot water', 'cylinder', 'immersion', 'combi'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'drainage',
    heading: 'Drainage',
    group: 'F Services',
    letter: 'F',
    ricsCode: 'F6',
    keywords: ['drain', 'soil stack', 'manhole', 'foul', 'surface water'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'common_services',
    heading: 'Common services',
    group: 'F Services',
    letter: 'F',
    ricsCode: 'F7',
    keywords: ['common services', 'communal heating', 'landlord supply'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'grounds_limitations',
    heading: 'Limitations to inspection (grounds)',
    group: 'G Grounds',
    letter: 'G',
    ricsCode: 'G.limitations',
    keywords: ['grounds limitations'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'garage_outbuildings',
    heading: 'Garage',
    group: 'G Grounds',
    letter: 'G',
    ricsCode: 'G1',
    keywords: ['garage', 'carport'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'permanent_outbuildings',
    heading: 'Permanent outbuildings and other structures',
    group: 'G Grounds',
    letter: 'G',
    ricsCode: 'G2',
    keywords: ['outbuilding', 'shed', 'store', 'summer house'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'grounds',
    heading: 'Other (grounds)',
    group: 'G Grounds',
    letter: 'G',
    ricsCode: 'G3',
    keywords: ['garden', 'grounds', 'drive', 'path', 'boundary', 'fence'],
    allowsRating: true,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'legal_advisers',
    heading: 'Regulation',
    group: 'H Issues for your legal advisers',
    letter: 'H',
    ricsCode: 'H1',
    keywords: ['legal', 'easement', 'covenant', 'planning', 'building control'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'legal_guarantees',
    heading: 'Guarantees',
    group: 'H Issues for your legal advisers',
    letter: 'H',
    ricsCode: 'H2',
    keywords: ['guarantee', 'warranty', 'nhbc', 'fensa'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'legal_other',
    heading: 'Other matters',
    group: 'H Issues for your legal advisers',
    letter: 'H',
    ricsCode: 'H3',
    keywords: ['other matters', 'legal other'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'risks',
    heading: 'Risks to the building',
    group: 'I Risks',
    letter: 'I',
    ricsCode: 'I1',
    keywords: ['risks to the building', 'structural risk', 'asbestos'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'risks_grounds',
    heading: 'Risks to the grounds',
    group: 'I Risks',
    letter: 'I',
    ricsCode: 'I2',
    keywords: ['risks to the grounds', 'contamination', 'Japanese knotweed'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'risks_people',
    heading: 'Risks to people',
    group: 'I Risks',
    letter: 'I',
    ricsCode: 'I3',
    keywords: ['risks to people', 'safety', 'lead', 'radon'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'risks_other',
    heading: 'Other risks or hazards',
    group: 'I Risks',
    letter: 'I',
    ricsCode: 'I4',
    keywords: ['other risks', 'hazards'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'energy',
    heading: 'Insulation',
    group: 'J Energy matters',
    letter: 'J',
    ricsCode: 'J1',
    keywords: ['insulation', 'loft insulation', 'cavity fill'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l3'],
  }),
  section({
    key: 'energy_heating',
    heading: 'Heating (energy)',
    group: 'J Energy matters',
    letter: 'J',
    ricsCode: 'J2',
    keywords: ['energy heating', 'heating controls'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l3'],
  }),
  section({
    key: 'energy_lighting',
    heading: 'Lighting',
    group: 'J Energy matters',
    letter: 'J',
    ricsCode: 'J3',
    keywords: ['lighting', 'low energy lamps'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l3'],
  }),
  section({
    key: 'energy_ventilation',
    heading: 'Ventilation',
    group: 'J Energy matters',
    letter: 'J',
    ricsCode: 'J4',
    keywords: ['ventilation', 'trickle vent', 'extract fan'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l3'],
  }),
  section({
    key: 'energy_general',
    heading: 'General (energy)',
    group: 'J Energy matters',
    letter: 'J',
    ricsCode: 'J5',
    keywords: ['energy general', 'energy matters'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l3'],
  }),
  section({
    key: 'valuation',
    heading: 'Valuation',
    group: 'J Valuation',
    letter: 'J',
    ricsCode: 'J.valuation',
    keywords: ['valuation', 'tenure', 'market value', 'area of property'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2'],
  }),
  section({
    key: 'declaration',
    heading: "Surveyor's declaration",
    group: 'K Surveyor’s declaration',
    letter: 'K',
    ricsCode: 'K',
    keywords: ['declaration', 'rics', 'surveyor', 'signed'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'what_to_do_now',
    heading: 'What to do now',
    group: 'L What to do now',
    letter: 'L',
    ricsCode: 'L',
    keywords: ['next steps', 'what to do', 'further investigation'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'rics_description',
    heading: 'Description of the RICS Home Survey',
    group: 'M Description of the service',
    letter: 'M',
    ricsCode: 'M',
    keywords: ['rics home survey', 'level 2', 'level 3', 'boilerplate'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'typical_house_diagram',
    heading: 'Typical house diagram',
    group: 'N Typical house diagram',
    letter: 'N',
    ricsCode: 'N',
    keywords: ['typical house', 'diagram'],
    allowsRating: false,
    allowsPhotos: true,
    levels: ['l2', 'l3'],
  }),
  section({
    key: 'notepad',
    heading: 'Note pad',
    group: 'Notes',
    letter: '',
    ricsCode: 'notes',
    keywords: ['note pad', 'notepad'],
    allowsRating: false,
    allowsPhotos: false,
    levels: ['l2', 'l3'],
  }),
] as const;

export type BuildingSurveySectionKey =
  (typeof BUILDING_SURVEY_SECTIONS)[number]['key'];

const SECTIONS_BY_KEY = new Map(
  BUILDING_SURVEY_SECTIONS.map((section) => [section.key, section]),
);

const SECTIONS_BY_RICS = new Map<string, BuildingSurveySection>();
for (const item of BUILDING_SURVEY_SECTIONS) {
  if (!SECTIONS_BY_RICS.has(item.ricsCode)) {
    SECTIONS_BY_RICS.set(item.ricsCode, item);
  }
}

export function buildingSurveySectionByKey(
  key: string,
): BuildingSurveySection | undefined {
  return SECTIONS_BY_KEY.get(key);
}

export function buildingSurveySectionByRicsCode(
  code: string,
): BuildingSurveySection | undefined {
  const normalized = code.trim();
  return (
    SECTIONS_BY_RICS.get(normalized) ??
    SECTIONS_BY_RICS.get(normalized.toUpperCase())
  );
}

export function resolveSurveySectionKey(
  value: string | null | undefined,
): string | undefined {
  if (!value) return undefined;
  if (SECTIONS_BY_KEY.has(value)) return value;
  return buildingSurveySectionByRicsCode(value)?.key;
}

export function surveyLevelForType(
  surveyType: string | null | undefined,
): SurveyLevel {
  return surveyType === 'rics_hss_l3' ? 'l3' : 'l2';
}

export function sectionsForSurveyType(
  surveyType: BuildingSurveyTypeKey | string | null | undefined,
): readonly BuildingSurveySection[] {
  const level = surveyLevelForType(surveyType);
  return BUILDING_SURVEY_SECTIONS.filter((section) =>
    section.levels.includes(level),
  );
}

export function ratedSurveySections(
  surveyType?: string | null,
): readonly BuildingSurveySection[] {
  return sectionsForSurveyType(surveyType ?? 'rics_hss_l3').filter(
    (section) => section.allowsRating,
  );
}

export function surveySectionDisplayLabel(
  section: Pick<BuildingSurveySection, 'heading' | 'ricsCode' | 'letter'>,
): string {
  if (/^[A-N]\d$/.test(section.ricsCode)) {
    return `${section.ricsCode} ${section.heading}`;
  }
  if (section.letter) {
    return `${section.letter} · ${section.heading}`;
  }
  return section.heading;
}

export function ricsCodeForSectionKey(key: string): string | null {
  return buildingSurveySectionByKey(key)?.ricsCode ?? null;
}
